// Supabase Edge Function: receives SOS SMS from Twilio and turns them into victim reports.
//
// Deploy:   supabase functions deploy twilio-sms-webhook --no-verify-jwt
// Secrets:  supabase secrets set TWILIO_AUTH_TOKEN=... MAPBOX_TOKEN=... PUBLIC_APP_URL=https://your-app
// Twilio:   Messaging webhook (HTTP POST) → https://<project>.supabase.co/functions/v1/twilio-sms-webhook
//
// Expected SMS body (generated by the victim app's SOS button):
//   RESCUEGRID SOS
//   Phone: +91XXXXXXXXXX
//   Location: 23.795000,86.430000        (or "Location: unknown")
//   Accuracy: High (~12m)
//   Type: rescue
//   Msg: 6 people stuck on roof

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const TWILIO_AUTH_TOKEN = Deno.env.get("TWILIO_AUTH_TOKEN") ?? "";
const MAPBOX_TOKEN = Deno.env.get("MAPBOX_TOKEN") ?? "";
const PUBLIC_APP_URL = (Deno.env.get("PUBLIC_APP_URL") ?? "").replace(/\/$/, "");

const VALID_SITUATIONS = ["food", "water", "medical", "rescue", "shelter", "missing"];
const SITUATION_URGENCY: Record<string, string> = {
  rescue: "critical",
  medical: "critical",
  missing: "urgent",
  food: "urgent",
  water: "urgent",
  shelter: "moderate",
};
const DUPLICATE_WINDOW_MS = 10 * 60 * 1000;

interface ParsedSMS {
  phone: string;
  latitude: number | null;
  longitude: number | null;
  situation: string;
  customMessage: string | null;
}

function twiml(message?: string) {
  const body = message
    ? `<Response><Message>${message.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")}</Message></Response>`
    : "<Response/>";
  return new Response(`<?xml version="1.0" encoding="UTF-8"?>${body}`, {
    status: 200,
    headers: { "Content-Type": "text/xml" },
  });
}

function normalizePhone(input: string): string {
  const hasPlus = input.trim().startsWith("+");
  let digits = input.replace(/\D/g, "");
  if (!hasPlus) {
    digits = digits.replace(/^0+/, "");
    if (digits.length === 10) digits = `91${digits}`;
  }
  return digits.length >= 10 ? `+${digits}` : input.trim();
}

export function parseSMSBody(body: string, fromPhone: string): ParsedSMS {
  const result: ParsedSMS = {
    phone: normalizePhone(fromPhone),
    latitude: null,
    longitude: null,
    situation: "rescue",
    customMessage: null,
  };

  const phoneMatch = body.match(/Phone:\s*([+\d\s\-()]{10,20})/i);
  if (phoneMatch) result.phone = normalizePhone(phoneMatch[1]);

  const locationMatch = body.match(/Location:\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)/i);
  if (locationMatch) {
    const lat = Number.parseFloat(locationMatch[1]);
    const lng = Number.parseFloat(locationMatch[2]);
    if (Math.abs(lat) <= 90 && Math.abs(lng) <= 180) {
      result.latitude = lat;
      result.longitude = lng;
    }
  }

  const typeMatch = body.match(/Type:\s*(\w+)/i);
  const type = typeMatch?.[1]?.toLowerCase();
  if (type && VALID_SITUATIONS.includes(type)) result.situation = type;

  const msgMatch = body.match(/Msg:\s*([\s\S]+)$/i);
  const message = msgMatch?.[1]?.trim();
  if (message && !/^(none|n\/a)$/i.test(message)) result.customMessage = message.slice(0, 500);

  return result;
}

/** Twilio request signature: base64(HMAC-SHA1(authToken, url + sorted(key+value))). */
async function isValidTwilioSignature(req: Request, params: URLSearchParams): Promise<boolean> {
  if (!TWILIO_AUTH_TOKEN) return true; // not configured — accept (development)
  const signature = req.headers.get("X-Twilio-Signature");
  if (!signature) return false;

  const data = [...params.keys()]
    .sort()
    .reduce((acc, key) => acc + key + (params.get(key) ?? ""), req.url);

  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(TWILIO_AUTH_TOKEN),
    { name: "HMAC", hash: "SHA-1" },
    false,
    ["sign"]
  );
  const mac = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(data));
  const expected = btoa(String.fromCharCode(...new Uint8Array(mac)));

  // Constant-time comparison
  if (expected.length !== signature.length) return false;
  let diff = 0;
  for (let i = 0; i < expected.length; i++) diff |= expected.charCodeAt(i) ^ signature.charCodeAt(i);
  return diff === 0;
}

async function reverseGeocode(lat: number, lng: number) {
  if (!MAPBOX_TOKEN) return { city: null, district: null };
  try {
    const res = await fetch(
      `https://api.mapbox.com/geocoding/v5/mapbox.places/${lng},${lat}.json?access_token=${MAPBOX_TOKEN}&types=place,district,locality`,
      { signal: AbortSignal.timeout(4000) }
    );
    const data = await res.json();
    const feature = data.features?.[0];
    const district = feature?.context?.find((c: { id: string }) => c.id.startsWith("district"))?.text;
    return { city: feature?.text ?? null, district: district ?? null };
  } catch {
    return { city: null, district: null };
  }
}

Deno.serve(async (req: Request) => {
  if (req.method !== "POST") {
    return new Response("Method not allowed", { status: 405 });
  }

  try {
    const rawBody = await req.text();
    const params = new URLSearchParams(rawBody);

    if (!(await isValidTwilioSignature(req, params))) {
      console.warn("Rejected SMS webhook call with invalid Twilio signature");
      return new Response("Forbidden", { status: 403 });
    }

    const from = params.get("From") ?? "";
    const body = params.get("Body") ?? "";

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
      auth: { persistSession: false },
    });

    if (!/RESCUEGRID/i.test(body)) {
      // A free-text reply (e.g. a landmark) from someone with an open report joins that thread.
      const { data: openReport } = await supabase
        .from("victim_report")
        .select("id")
        .eq("phone_no", normalizePhone(from))
        .not("status", "in", "(resolved,duplicate)")
        .gte("created_at", new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString())
        .order("created_at", { ascending: false })
        .limit(1);

      if (openReport && openReport.length > 0 && body.trim()) {
        await supabase.from("message").insert({
          content: `[SMS] ${body.trim().slice(0, 1000)}`,
          sender_type: "victim",
          victim_report_id: openReport[0].id,
        });
        return twiml("RescueGrid: message received and passed to the rescue team.");
      }

      return twiml("RescueGrid: to report an emergency, open the RescueGrid app and tap SOS, or call the helpline.");
    }

    const parsed = parseSMSBody(body, from);

    // Retries / repeated taps: attach to the recent open report instead of duplicating it.
    const { data: existing } = await supabase
      .from("victim_report")
      .select("id")
      .eq("phone_no", parsed.phone)
      .eq("situation", parsed.situation)
      .neq("status", "resolved")
      .gte("created_at", new Date(Date.now() - DUPLICATE_WINDOW_MS).toISOString())
      .order("created_at", { ascending: false })
      .limit(1);

    if (existing && existing.length > 0) {
      await supabase.from("message").insert({
        content: parsed.customMessage ? `[SMS] ${parsed.customMessage}` : "[SMS] Follow-up SOS received",
        sender_type: "victim",
        victim_report_id: existing[0].id,
      });
      return twiml("RescueGrid: we already have your report and help is being coordinated. Stay safe.");
    }

    const { city, district } =
      parsed.latitude !== null && parsed.longitude !== null
        ? await reverseGeocode(parsed.latitude, parsed.longitude)
        : { city: null, district: null };

    const { data: report, error } = await supabase
      .from("victim_report")
      .insert({
        phone_no: parsed.phone,
        latitude: parsed.latitude,
        longitude: parsed.longitude,
        city,
        district,
        situation: parsed.situation,
        custom_message: parsed.customMessage
          ? `[via SMS] ${parsed.customMessage}`
          : "[via SMS]",
        status: "open",
        urgency: SITUATION_URGENCY[parsed.situation] ?? "moderate",
      })
      .select("id")
      .single();

    if (error || !report) {
      console.error("Database error:", error);
      // Still tell the victim to call — never leave them without a response.
      return twiml("RescueGrid: we could not register your SMS. Please call the helpline immediately.");
    }

    console.log(`Created victim_report ${report.id} from SMS`);

    const ref = report.id.slice(0, 4).toUpperCase();
    const trackLink = PUBLIC_APP_URL ? ` Track: ${PUBLIC_APP_URL}/report/status/${report.id}` : "";
    const locationNote = parsed.latitude === null ? " We did not receive your location - reply with a landmark." : "";
    return twiml(`RescueGrid: help request received (ref ${ref}).${locationNote}${trackLink}`);
  } catch (err) {
    console.error("Edge function error:", err);
    return twiml("RescueGrid: something went wrong. Please call the helpline.");
  }
});
